import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Barber Shop | Crie seus agendamentos e mande aquela régua sinistra
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full w-full bg-black text-white">
        <header className="border-b border-slate-500">
          <div>Phone: (41) 99194-4035</div>
        </header>
      </div>
    </>
  );
}
